<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>

delete from PUB.TMP_NAME;

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP02001', '首頁');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03000', '賬戶服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03001', '賬戶一覽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03009', '賬戶管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03010', '添加/刪除賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03015', '凍結賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03023', '交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03024', '賬戶交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03027', '月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03028', '開通/取消電子結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03031', '下載電子結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03036', '申請過往月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03039', '支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03040', '申請支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03045', '報失支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03050', '存摺報失');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03055', '資產證明書申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03060', '網上交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04000', '轉賬匯款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04001', '普通轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04011', '同名戶轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04021', '第三者轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04031', '中銀澳分行轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04041', '批量轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04061', '收款人名冊管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04071', '轉賬交易查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04100', '二維碼轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04101', '開通/關閉服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04111', '二維碼轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04121', '二維碼收款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04131', '交易記錄查詢/撤消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04200', '手機號轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04201', '開通/關閉服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04211', '手機號轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04221', '交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04300', '網上匯款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04301', '匯款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04311', '交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04400', '預約/周期轉賬匯款管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05000', '繳費支付');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05001', '網上繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05002', '繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05005', '交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05010', '管理繳費單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05022', '自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05023', '申請自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05030', '取消/修改自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05043', '愛心捐款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05044', '愛心捐款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05050', '交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05200', '繳費單查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06000', '個人理財');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06001', '財富及投資總覽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06002', '外匯買賣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06004', '外匯買賣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06010', '交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06015', '定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06016', '新造定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06022', '提取定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06028', '查看及更改續期方式');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06034', '風險承受能力評估');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06035', '風險承受能力評估');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06038', '旅遊保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06039', '查看保費及資訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06040', '投保人管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06041', '查看評估等級');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06047', '購買旅遊保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06054', '購買記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06057', '下載保單條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06058', '下載索償表格');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06059', '查看使用聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06060', '計算器');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06066', '報失定期存款證明書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06070', '金融資訊及工具');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07000', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07002', '信用卡申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07007', '網上繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07013', '優惠活動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07015', '信用卡賬戶信息管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07021', '查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07022', '繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07028', '查詢信用卡結餘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07029', '交易查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07030', '查詢交易記錄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07032', '查詢電子月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07038', '額度管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07039', '辦理[月結單分期付款]');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07040', '[月結單分期付款]計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07041', '主卡額度申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07042', '附屬卡額度申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07045', '查詢交易記錄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07050', '禮品換領');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07051', '選擇禮品');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07053', '換領禮品查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07056', '網上購物安保服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07057', '「一次性密碼」網上保安服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07061', '認證記錄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08000', '個人貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08001', '個人貸款申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08002', '申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08008', '查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08015', '貸款詳情查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08020', '貸款結欠查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08023', '還款明細查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08027', '抵押物業資料查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09000', '提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09001', '申請提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09011', '補發提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09016', '報失提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09022', '凍結提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10000', '預約服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10009', '預約理財產品服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10013', '預約服務管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10400', '預約/周期轉賬匯款管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10500', '網點預約排隊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10600', '網點遠程取號');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11000', '安全中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11001', '個人信息管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11007', '網上銀行密碼修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11010', '短訊提醒服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11021', '安全密碼器凍結');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11024', '交易限額設置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11028', '短訊密碼認證設定');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11029', '關閉短訊密碼認證版');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11035', '修改已綁定之手機號碼');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11040', '暫停網銀服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11044', '調查問卷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11045', '問卷填寫');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11048', '問卷記錄查看');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12000', '股票服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12001', '股票買賣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12002', '認購新股');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12004', '認購結果查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12005', '串流股票報價服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12019', '查看新股資訊及認購');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12026', '股票賬戶資料');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12027', '按金調撥');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12034', '申請串流股票報價服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12038', '取消串流股票報價服務');



</body>
</html>