<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>

delete from PUB.TMP_NAME;

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060471', '地區一$#$指定地區(包括：中國、香港、緬甸、泰國、馬來西亞、新加坡、印尼、菲律賓、汶萊、越南、韓國、柬浦寨、老撾、台灣、日本、尼泊爾、巴基斯坦、印度)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060472', '地區二$#$全球(美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060473', '地區三$#$全球');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100001', '往來帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100002', '儲蓄帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100003', '多幣寶帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100004', '定期帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100005', '靈活理財帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100006', '股票帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100007', '貸款帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100008', '一般卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100009', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100011', '自動轉帳付款證明書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100012', '往來月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100013', '多幣寶壓縮結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100014', 'MI斬倉單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100015', '定期結清單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100016', '儲蓄帳戶的壓縮結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100017', 'MI結清單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100018', '親臨領取');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100019', '公司注冊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100020', '貿易促進局');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100021', '申請簽證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100022', '贊助');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100023', '其它');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100024', '中文(簡體)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100025', '中文(繁體)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100026', '英文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100027', '不動戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100028', '正常');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100029', '全部');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100030', '資產');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100031', '負債');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100032', '消費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100033', '管道');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100034', '批量');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100035', '投資');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100036', '獎勵');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100037', '金額');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100038', '次數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100039', '批量轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100040', '定投計劃撤銷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100041', '加息贏簽約');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100042', '網銀中加挂借記卡或信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100043', '貴金屬委托撤銷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100044', '信用卡還款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100045', '一站式轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100046', '存入定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100047', '理財產品預約');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100048', '黃金定投開戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100049', '定投計劃設置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100050', '生活繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100051', '基金開戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100052', '基金轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100053', '個人貸款申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100055', '簽約網銀互聯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100056', '旅遊保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100057', '其它');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100058', '同名戶轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100059', '第三者轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100060', '轉帳至中銀澳門分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100062', '電匯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100063', '信匯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100065', '速匯金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100066', '匯入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100067', '匯出');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100068', '成功');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100069', '失敗');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100070', '待處理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100071', '未知');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100072', '已審核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100073', '審核中');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100074', '未審核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100075', '不作續期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100076', '本金續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100077', '本息續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100078', '本息增額續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100079', '本息減額續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100080', '本息清還');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100081', '本人');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100082', '配偶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100083', '家人');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100084', '子女');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100085', '男');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100086', '女');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100087', '指定地區(包括:中國、香港、緬甸等)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100088', '全球(美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100089', '全球(美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100090', '標准計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100091', '高級計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100092', '未婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100093', '已婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100094', '離婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100095', '未啓動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100096', '已啓動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100101', '樓宇按揭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100102', '升學貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100103', '汽車貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100104', '預期還款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100105', '正常還款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100106', '全額還款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100107', '部分還款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100108', '853');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100109', '86');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100110', '單次預約轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100111', '周期轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100112', '每月一次');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100113', '每周一次');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100114', '收款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100115', '支款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100116', '第三方賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100117', '全部');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100118', '澳中銀賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100119', '電費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100120', '水費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100121', '煤氣費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100122', '電視費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100123', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100124', '3.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100125', '2.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100127', '2.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100128', '2.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100129', '1.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100130', '1.50%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100131', '1.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100132', '1.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100133', '0.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100134', '0.50%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100135', '0.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100136', '0.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100137', '總行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100138', '新橋分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100139', '寶翠分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100140', '紅街市分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100141', '黑沙環分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100142', '荷蘭園分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100143', '十月初五街分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100144', '普京分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100145', '一山分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100146', '渡船街分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100147', '高士德分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100148', '筷子基分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100149', '百老匯分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100150', '新口岸分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100151', '1年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100152', '2年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100153', '星期一');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100154', '星期二');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100155', '星期三');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100156', '星期四');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100157', '星期五');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100158', '1');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100159', '2');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100160', '3');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100161', '4');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100162', '5');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100163', '6');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100164', '7');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100165', '8');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100166', '9');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100167', '10');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100168', '11');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100169', '12');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100170', '13');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100171', '14');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100172', '15');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100173', '16');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100174', '17');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100175', '18');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100176', '19');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100177', '20');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100178', '21');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100179', '22');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100180', '23');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100181', '24');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100182', '25');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100183', '26');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100184', '27');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100185', '28');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100186', '29');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100187', '30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100188', '31');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100200', '世界宣明會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100201', '澳門紅十字會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100202', '澳門同善堂');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100203', '奧比斯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100204', '澳門明愛');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100205', '澳門聾人協會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100206', '澳門弱智人士服務協會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100207', '澳門扶康會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100210', '地震');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100211', '水災');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100212', '疾病');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100221', '汶川地震');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100224', '汶川水災');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100227', '汶川疾病');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100230', '電費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100231', '水費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100232', '話費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100233', '稅收');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100234', '電視費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100235', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100238', '督課中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100239', '大豐投資');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100240', '電訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100242', '物業管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100243', '水電能源');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100280', '電信');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100281', '社保');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100282', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100283', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100300', '澳門電力公司');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100302', '自來水公司');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100303', '澳門電訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100304', '港幣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100305', '澳幣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100307', '股票服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100308', '提款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100309', '貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100310', '外幣兌換');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100311', '定期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100312', '轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100313', '保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100314', '匯款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100315', '保管箱');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100316', '存款證明書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100317', '月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100318', '提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100319', '外匯買賣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100320', '金融投資理財中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100323', '預約理財產品服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100324', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100325', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100326', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100327', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100328', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100329', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100330', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100331', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100332', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100333', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100334', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100336', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100337', '澳門特別行政區居民身分證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100338', '香港居民身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100339', '中國身分證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100340', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100341', '中學');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100342', '大專');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100343', '大學或以上');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100344', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100345', '已婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100346', '未婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100347', '離婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100348', '鳏寡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100349', '分別財產制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100350', '一般共同財產制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100351', '取得共同財產制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100352', '取得財產分享制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100353', '自置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100354', '親人擁有');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100355', '按揭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100356', '租用');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100357', '雇員');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100358', '東主');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100359', '公司股東');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100360', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100361', '薪金收入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100362', '經營收入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100363', '租金收入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100364', '是');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100365', '否');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100366', '大豐銀行調查問卷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100367', '未提交');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100368', '已提交');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100369', '未通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100370', '已通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100372', '凍結');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100373', '正常');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100374', '鎖定');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100375', '待激活');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100431', '香港身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100432', '澳門識別證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100433', '澳門居民身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100434', '臨時居民身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100435', '營業稅檔案編號');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100436', '九零登記收據');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100437', '九零登記無證行動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100438', '非本地勞工證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100439', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100440', '澳門身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100441', '中國身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100442', '台灣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100443', '09:00-10:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100444', '10:00-11:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100445', '11:00-12:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100446', '14:00-15:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100447', '15:00-16:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100448', '16:00-17:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100449', '09:00-09:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100450', '10:00-10:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100451', '11:00-11:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100452', '14:45-15:30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100453', '15:45-16:30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100454', '住宅');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100455', '車位');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100456', '商鋪');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100457', '寫字');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100458', '廠房');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100459', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100460', '一手');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100461', '二手');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100462', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100463', '現樓');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100464', '樓花');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100465', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100512', '澳門特別行政區居民身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100600', '本澳升學貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100601', '海外升學貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100667', '中國太平保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100668', '聯豐亨保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100669', '保單條款(中文版)下載');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100670', '保單條款(英文版)下載');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100671', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100672', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100673', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100674', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100675', '是');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100676', '否');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100677', '中文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100678', '英文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100679', '有');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100680', '無');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100682', '氹仔');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100683', '路環');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100690', '澳門');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100900', '申請中');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100901', '已通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100902', '未通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101001', '凍結');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101007', '部分放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101100', '由申請日起7個工作日之後，三個自然月之內');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101101', '由申請日起5個工作日之後，三個自然月之內');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120001', '現時價');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120002', '延時價');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120003', '由股票賬戶轉入關聯存款戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120004', '由關聯存款戶轉入股票賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121001', '全數成盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121002', '部份成盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121003', '全數失敗');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121004', '全數取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121005', '部份取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121006', '尚未覆盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14001', '已核准');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14002', '全額放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14003', '到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200011', '基礎參數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200012', '多語言頁面標簽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200013', '錯誤碼參數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200014', '溫馨提示');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200101', '基礎參數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200102', '錯誤碼參數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200103', '多語言標簽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200371', 'IACTF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202701', '存款業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202702', '匯款業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202703', '樓宇按揭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('233', '結清');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('234', '取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('235', '重整');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('236', '展期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('237', '取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3026', '轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3027', '繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3028', '匯款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3029', '股票');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3030', '自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3031', '1');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400060', '批量轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4001', '待銷戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4002', '關戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400720', '基礎查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400721', '高級查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400723', '最近1個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400724', '今天');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400725', '最近3個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4010', '存款賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4011', '貸款賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4012', '信用卡賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4013', '股票賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4014', '靈活理財');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402021', '當天交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402022', '一星期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402023', '一個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402024', '三個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40430', '批量批次次數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40731', '全部');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40732', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40733', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40735', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40736', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40737', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40738', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40739', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40740', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40741', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600001', '你的父母在哪個城市訂婚的？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600002', '你爺爺的出生地在哪？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600003', '你第一次出國的年齡？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600004', '你初中的學校是哪裏？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600005', '你養的第一個寵物的名字是什麽？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600006', '你的駕駛執照的號碼是什麽？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600007', '你爸爸的出生日期？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600008', '你最喜歡的餐廳的名字是什麽？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600009', '你小學三年級的老師名字？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600502', '特別聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600503', '投保人聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600504', '聯豐亨【樂逍遙】');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600505', '太平洋保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60475', '標准計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60476', '高級計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60478', '基本計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60479', '超級計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60480', '至尊計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60531', '分組一');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60532', '分組二');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60533', '分組三');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60534', '分組四');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700001', '等級');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700002', '積分');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700003', '等級');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700004', '積分');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700005', '等級');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700006', '積分');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70001', '貸款應還款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700011', '升學貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700012', '汽車貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700013', '一星期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700014', '二星期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700015', '一個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700016', '二個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700017', '三個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700018', '六個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700019', '十二個月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70002', '貸款逾期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700020', '3到7個工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700021', '3到7個工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700022', '3到7個工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700023', '3到7個工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700024', '大豐網上銀行協議書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700025', '安全問題最大錯誤次數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700026', '不循環');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700027', '按月循環');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700028', '按年循環');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700029', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70003', '定期到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700030', '親戚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700031', '父母');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700035', '3年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700036', '4年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700037', '5年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700038', '10年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700039', '30年（後台可以維護）');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70004', '預約開戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700042', '結清');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700043', '已取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700046', '已重整');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700047', '取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700048', '是');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700049', '否');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70005', '預約理財產品');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700052', 'ATM無卡提現協議文本');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700053', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700054', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700055', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700056', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700057', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700058', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700059', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70006', '領取提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700060', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700061', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700062', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700063', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700064', 'TFG');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700065', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70007', '領取支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700073', '地區一$#$指定地區(包括：中國、香港、緬甸、泰國、馬來西亞、新加坡、印尼、菲律賓、汶萊、越南、韓國、柬浦寨、老撾、台灣、日本、尼泊爾、巴基斯坦、印度)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700074', '地區二$#$全球(美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700075', '地區三$#$全球');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700077', '6年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700078', '7年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700079', '8年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70008', '領取紙質月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700080', '9年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700082', '雇員');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700083', '東主');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700084', '公司股東');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700085', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70009', '領取賬戶資金餘額證明書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700091', '穩健型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700092', '謹慎型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700093', '平衡型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700094', '進取型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700095', '投機型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700096', '股票串流服務密碼');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700098', '澳洲元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700099', '加拿大元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70010', '生日節日祝福');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700100', '人民幣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700101', '港元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700102', '日本元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700103', '澳門元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700104', '紐西蘭元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700105', '瑞士法郎');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700106', '英鎊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700107', '美鈔');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700108', '歐羅');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700109', '美元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70011', '風險投資問卷期限到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70012', '旅遊保險起始日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70013', '旅遊保險到期日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700131', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700132', '保險業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700133', '11年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700134', '12年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700135', '13年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700136', '14年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700137', '15年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700138', '16年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700139', '17年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70014', '自設提示');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700140', '18年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700141', '19年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700142', '20年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700143', '21年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700144', '22年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700145', '23年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700146', '24年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700147', '25年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700148', '26年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700149', '27年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70015', '銀行假期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700150', '28年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700151', '你生日的這天裏，有我的祝福有我的問候：祝開開心心，心想事成。');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700152', '生日，就是一個起點，一切從這裏開始！祝你生日快樂！');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700153', '生日要喝彩，壽星才愉快。親愛的朋友，生日快樂。');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700154', '生日祝福你，萬事順著你！');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700155', '祝您壽與天齊，並祝美好明天！');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70016', '預約轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700171', '已通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700172', '未通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700173', '已申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700174', '已過期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700176', '大豐網上銀行協議書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700181', '黃金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700182', '基金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700183', '國債');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700194', '核准');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700195', '部份放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700196', '全部放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700197', '到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700198', '29年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700199', '押匯業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70020', '不作續期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700200', '開戶及賬戶維護服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700201', '工商貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700202', '其他查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700203', '表揚/ 投訴/ 意見');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700204', '股票金融投資');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70021', '本金續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700218', '賬戶資產');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700219', '現金資產');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70022', '本息續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700220', '股票資產');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700221', '貸款資產');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700222', '全部資產');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700223', '公司注冊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700224', '貿易促進局');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700225', '簽證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700226', '贊助');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700227', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70023', '本息增額續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700235', '提款卡/ 自動櫃員機');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700236', '電子渠道');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700237', '電信繳費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70024', '本息減額續存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70025', '本息清還');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700250', '全額證明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700251', '定額證明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700252', '致各有關人士');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700253', '其它');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700254', '郵寄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700255', '親臨領取');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700256', '1份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700257', '2份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700258', '3份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700259', '5份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700260', '4份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700261', '中文簡體');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700262', '中文繁體');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700263', '英文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700264', '澳門身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700265', '香港身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700266', '大陸身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700267', '護照');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700268', '全數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700269', '整數');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700270', '等于');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700271', '不少于');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700272', '編輯中');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700273', '已撤銷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700274', '審核不通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700275', '提交待審核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700276', '審核通過/已發布');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700277', '創建');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700278', '更新');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700279', '刪除');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700280', '撤消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700281', '停用');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700311', '申請成功');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700312', '申請失敗');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700313', '6份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700314', '7份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700315', '8份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700316', '9份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700317', '10份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700328', '+853');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700329', '+86');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700330', '+852');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700534', '郵寄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700535', '親臨領取');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700536', '郵寄地址');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700537', '領取地址');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700538', '總行營業部的金融投資理財中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700551', '首頁廣告');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700552', '產品資訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700553', '登陸頁廣告');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700568', '標准計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700569', '高級計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700570', '基本計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700571', '超級計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700572', '至尊計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700573', '聯豐亨保險-標准計劃');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700574', '服務條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700575', '個人貸款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700576', '個人理財');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700577', '旅遊保險協議');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700578', 'ATM無卡提現協議文本');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700579', '首次登錄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700580', '5手機號轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700581', '網上通-理財服務使用條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700582', '移動通-理財服務使用條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700583', '商務網上理財服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700584', '二維碼轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700585', '無卡提現');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700586', '自動轉賬直接付款授權書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700587', '串流報價服務條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700588', '電子結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700589', '監管機構');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700590', '軟件使用聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700591', '網上銀行保安資訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700592', '網上銀行隱私政策聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700639', '200');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700640', '54.00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700641', '香港居民身份證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700655', '澳洲元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700656', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700657', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700658', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700659', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700660', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700661', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700662', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700663', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700664', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700665', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700666', 'TFG');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700667', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700816', '60.00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700900', '查詢未添加賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700901', '網銀登錄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700902', '網上交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700903', '刪除附屬賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700904', '添加附屬賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700905', '手續費扣費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700906', '愛心捐款(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700907', '存折報失(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700908', '開通股票串流服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700909', '關閉股票串流服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700910', '網上銀行密碼修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700911', '設置安全問題');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700912', '手機號認證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700913', '交易限額設置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700914', '驗證證件號(忘記密碼或登錄代號)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700915', '驗證安全問題(忘記密碼)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700916', '重置密碼(忘記密碼)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700917', '驗證安全問題(忘記登錄代號)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700918', '同名戶轉賬(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700919', '同名戶轉賬(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700920', '第三者轉賬(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700921', '第三者轉賬(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700922', '中銀澳分行轉賬(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700923', '中銀澳分行轉賬(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700924', '批量轉賬(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700925', '批量轉賬(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700926', '查詢簽約第三者帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700927', '添加/修改第三者賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700928', '查詢中銀澳分賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700929', '添加/修改中銀澳分賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700930', '添加預約轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700931', '修改預約轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700932', '預約狀態修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700933', '收款人名冊管理(修改)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700934', '收款人名冊管理(刪除)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700935', '收款人名冊管理(頭像編輯)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700936', '驗證第三者賬號首次轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700937', '開通二維碼轉賬服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700938', '開通手機號轉賬服務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700939', '新增匯款(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700940', '新增匯款(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700941', '開通電子月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700942', '關閉電子月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700943', '申請過往月結單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700944', '申請旅遊保險(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700945', '申請旅遊保險(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700946', '修改別名');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700947', '凍結賬戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700948', '申請支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700949', '報失支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700950', '報失支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700951', '存折報失');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700952', '資產證明書申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700953', '繳費稅收(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700954', '繳費稅收(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700955', '繳三費(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700956', '繳三費(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700957', '有限電視繳費(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700958', '有限電視繳費(提交)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700959', '繳費中國電信(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700960', '繳費中國電信(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700961', '繳費社保(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700962', '繳費社保(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700963', '信用卡還款(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700964', '信用卡還款(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700965', '新增繳費單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700966', '刪除繳費單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700967', '修改繳費單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700968', '申請自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700969', '修改自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700970', '刪除自動轉賬');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700971', '愛心捐款(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700972', '投資組合');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700973', '股票當天交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700974', '股票信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700975', '現時價');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700976', '落盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700977', '改盤(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700978', '獲取延時報價時股票信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700979', '撤盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700980', '股票交易詳情');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700981', '改盤(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700982', '股票當月交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700983', '可供申請IPO列表查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700984', '認證新股詳細查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700985', '認證新股');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700986', '股票賬戶資料');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700987', '按金調撥');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700988', '外匯買賣(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700989', '外匯買賣(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700990', '新造定期(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700991', '新造定期(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700992', '提取定期(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700993', '提取定期(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700994', '網銀個人資料修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700995', '修改手機號');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700996', '暫停網銀');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700997', '預約理財產品');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700998', '貸款申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700999', '短訊提醒服務開通');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701000', '短訊提醒服務關閉');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701001', '交易限額設置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701002', '手機號轉賬(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701003', '手機號轉賬(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701004', '二維碼轉賬(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701005', '二維碼轉賬(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701006', '添加投保人信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701007', '修改投保人信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701008', '刪除投保人信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701009', '申請提款卡(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701010', '補發提款卡(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701011', '報失提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701012', '凍結提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701013', '預約服務管理(修改)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701014', '預約服務管理(取消)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701015', '賬戶交易記錄查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701016', '二維碼收款(預覽)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701017', '二維碼收款(確認)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701018', '更改續期方式');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701019', '報失定期存款證明書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701020', '取消貸款申請');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701021', '問卷填寫');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701023', '查詢股票信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701024', '買入/賣出');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701025', '持倉組合');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701026', '改盤/撤盤預覽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701027', '撤盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701028', '股票交易詳情');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701029', '改盤提交');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701030', '當月交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701031', '可供申請IPO列表');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701032', '認購新股詳細查詢');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701033', '認購新股');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701034', '股票賬戶資料');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701035', '按金調撥');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701036', '交易檢查');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701037', '報失/補發提款卡');



</body>
</html>