<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>

delete from PUB.TMP_NAME;

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060471', 'Area 1 $#$Restricted Area (包括: In國、 Hong Kong 、 緬甸、 泰國、 馬來西亞、 New 加坡、 印尼、 菲律賓、 汶萊、 越南、 韓國、 柬浦寨、 老撾、 台灣、 Day Unit 、 尼泊爾、 巴基斯坦、 印度)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060472', 'District 二$#$Worldwide (美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060473', 'District 三$#$Worldwide ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100001', 'Current 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100002', 'Savings 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100003', 'Multi-Currency A/C 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100004', 'Fix-Deposit 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100005', 'Financial Flexibility 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100006', 'Stock 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100007', 'Loan 帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100008', 'General 卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100009', 'Credit Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100011', 'Auto 轉帳Pay Certificate ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100012', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100013', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100014', 'MI');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100015', 'Fix-Deposit 結清單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100016', 'Savings 帳戶壓縮Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100017', 'MI結清單');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100018', 'To receive ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100019', 'Company Note 冊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100020', '貿易促進局');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100021', 'Request Visa ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100022', 'Sponsor ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100023', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100024', 'English (簡體)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100025', 'English (繁體)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100026', 'English ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100027', 'No 動戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100028', 'Normal ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100029', 'All ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100030', 'Assets ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100031', 'Liabilities ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100032', '消費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100033', '管道');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100034', 'Batch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100035', 'Investment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100036', '獎勵');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100037', 'Amount ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100038', 'Times ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100039', 'Batch 轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100040', '定投Plan Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100041', '加息贏簽約');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100042', 'iBanking In加挂借記卡或Credit Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100043', '貴金屬委托Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100044', 'Credit Card Repayment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100045', '一站式轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100046', 'Deposit Fixed Deposit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100047', '理財產品Appointment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100048', '黃金定投Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100049', '定投Plan Setting ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100050', '生活Payment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100051', '基金Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100052', '基金轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100053', 'Personal Loan Request ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100055', '簽約iBanking 互聯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100056', 'Insurance ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100057', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100058', '同名戶轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100059', '第三者轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100060', '轉帳To BOC Macau Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100062', 'Telegraphic Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100063', 'Cenway ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100065', 'Moneygram ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100066', 'Inward ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100067', 'Outward ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100068', 'Success ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100069', 'Failed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100070', 'Pending ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100071', 'Unknown ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100072', 'Has 審核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100073', '審核In');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100074', 'Not 審核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100075', 'No 作續期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100076', 'Principal Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100077', 'Unit 息Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100078', 'Unit 息增額Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100079', 'Unit 息減額Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100080', 'Unit 息清還');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100081', 'Policyholder ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100082', 'Spouse ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100083', 'Family ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100084', 'Son/Daughter ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100085', 'Man ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100086', 'Woman ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100087', 'Restricted Area (包括:In國、 Hong Kong 、 緬甸等)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100088', 'Worldwide (美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100089', 'Worldwide (美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100090', '標准Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100091', 'Deluxe Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100092', 'Single ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100093', 'Married ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100094', 'Divorced ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100095', 'Not 啓動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100096', 'Has 啓動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100101', 'HIP ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100102', 'Up 學Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100103', 'Auto Loans ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100104', '預期Repayment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100105', 'Ordinary Repayment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100106', '全額Repayment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100107', '部分Repayment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100108', '853');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100109', '86');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100110', 'Single Pre-set Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100111', 'Cycle 轉帳');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100112', 'Once a month ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100113', '每Mon Times ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100114', 'Credit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100115', 'Debit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100116', '第三方Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100117', 'All ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100118', '澳BOC Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100119', 'Electricity ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100120', 'Water ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100121', 'Gas bill ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100122', 'Cable TV ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100123', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100124', '3.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100125', '2.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100127', '2.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100128', '2.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100129', '1.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100130', '1.50%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100131', '1.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100132', '1.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100133', '0.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100134', '0.50%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100135', '0.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100136', '0.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100137', 'Total Line ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100138', 'New 橋Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100139', '寶翠Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100140', '紅街市Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100141', '黑沙環Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100142', '荷蘭園Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100143', '十Month 初五街Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100144', '普京Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100145', '一山Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100146', '渡船街Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100147', '高士德Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100148', '筷子基Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100149', '百老匯Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100150', 'New 口岸Branch ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100151', '1Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100152', '2Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100153', 'Week 一');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100154', 'Week 二');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100155', 'Week 三');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100156', 'Week 四');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100157', 'Week 五');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100158', '1');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100159', '2');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100160', '3');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100161', '4');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100162', '5');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100163', '6');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100164', '7');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100165', '8');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100166', '9');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100167', '10');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100168', '11');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100169', '12');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100170', '13');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100171', '14');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100172', '15');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100173', '16');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100174', '17');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100175', '18');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100176', '19');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100177', '20');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100178', '21');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100179', '22');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100180', '23');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100181', '24');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100182', '25');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100183', '26');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100184', '27');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100185', '28');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100186', '29');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100187', '30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100188', '31');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100200', '世界宣明會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100201', 'Macau 紅十字會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100202', 'Macau 同善堂');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100203', '奧比斯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100204', 'Macau 明愛');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100205', 'Macau 聾Persons 協會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100206', 'Macau Weak 智Persons 士Service 協會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100207', 'Macau 扶康會');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100210', '地震');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100211', '水災');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100212', '疾病');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100221', '汶川地震');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100224', '汶川水災');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100227', '汶川疾病');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100230', 'Electricity ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100231', 'Water ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100232', '話費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100233', '稅收');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100234', 'Cable TV ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100235', 'Credit Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100238', '督課Center ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100239', 'TaiFung Investment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100240', '電訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100242', '物業Management ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100243', '水電能源');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100280', '電信');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100281', '社保');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100282', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100283', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100300', 'Macau 電力Company ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100302', 'From 來水Company ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100303', 'Macau 電訊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100304', 'HKD ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100305', '澳幣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100307', 'Stock Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100308', '提款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100309', 'Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100310', 'Foreign Exchange ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100311', 'Fix-Deposit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100312', 'Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100313', '保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100314', 'Remittance ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100315', '保管箱');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100316', 'Deposits Certificate ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100317', 'Monthly Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100318', 'ATM card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100319', 'Foreign Exchange ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100320', 'Financial Investment 理財Center ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100323', 'Financial Products and Services Appointment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100324', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100325', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100326', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100327', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100328', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100329', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100330', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100331', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100332', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100333', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100334', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100336', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100337', 'Macau 特別Line 政Area 居民身分證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100338', 'Hong Kong 居民身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100339', 'In國身分證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100340', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100341', 'Secondary ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100342', 'Tertiary ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100343', '大學或以上');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100344', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100345', 'Married ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100346', 'Single ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100347', 'Divorced ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100348', '鳏寡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100349', '分別財產制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100350', 'General Total 同財產制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100351', '取得Total 同財產制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100352', '取得財產分享制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100353', 'Self-Owned ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100354', '親Persons 擁Yes ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100355', 'Mortgaged ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100356', 'Rented ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100357', '雇員');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100358', 'Employee ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100359', 'Company Unit 東');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100360', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100361', '薪金Income ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100362', '經營Income ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100363', 'Rental Income ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100364', 'Yes ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100365', 'No ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100366', 'TaiFung Bank Questionnaire ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100367', 'Not Submit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100368', 'Submitted ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100369', 'Not by ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100370', 'Has passed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100372', 'Frozen ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100373', 'Normal ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100374', '鎖定');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100375', '待激活');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100431', 'Hong Kong Identity Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100432', 'Macau 識別證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100433', 'Macau 居民身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100434', '臨時居民身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100435', '營業稅檔案No. ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100436', '九零登記收據');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100437', '九零登記No 證Line 動');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100438', 'Non-Local 勞工證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100439', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100440', 'Macau 身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100441', 'Chinese Identity Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100442', '台灣');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100443', '09:00-10:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100444', '10:00-11:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100445', '11:00-12:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100446', '14:00-15:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100447', '15:00-16:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100448', '16:00-17:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100449', '09:00-09:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100450', '10:00-10:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100451', '11:00-11:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100452', '14:45-15:30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100453', '15:45-16:30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100454', 'Residential ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100455', 'Car Park ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100456', '商鋪');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100457', 'Office ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100458', 'Factory ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100459', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100460', 'Primary ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100461', 'Second Hand ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100462', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100463', 'HIP,HEP ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100464', 'EM ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100465', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100512', 'BIR ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100600', 'Educational Loan for Local study Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100601', 'Educational Loan for Overseas study Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100667', 'In國太平保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100668', 'Luen Fung Hang Insurance Company Limited ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100669', '保單條款(English 版)Download ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100670', '保單條款(English Vision )Download ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100671', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100672', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100673', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100674', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100675', 'Yes ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100676', 'No ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100677', 'English ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100678', 'English ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100679', 'Yes ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100680', 'No ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100682', 'Taipa ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100683', 'Coloane ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100690', 'Macau ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100900', 'Pending ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100901', 'Has passed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100902', 'Not by ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101001', 'Frozen ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101007', '部分放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101100', 'From Request Day 起7Unit 工作Day 之後, 三Unit From 然Month 之內');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101101', 'From Request Day 起5Unit 工作Day 之後, 三Unit From 然Month 之內');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120001', 'Current ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120002', 'Delayed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120003', 'From stock account to linked deposit account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120004', 'From linked deposit account to stock account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121001', 'All 成盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121002', '部Unit 成盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121003', 'All Failed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121004', 'All Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121005', '部Unit Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121006', '尚Not 覆盤');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14001', 'Has 核准');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14002', '全額放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14003', 'To 期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200011', '基礎參Number(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200012', '多Language Page 標簽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200013', '錯誤碼參Number(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200014', 'Friendly Reminder ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200101', '基礎參Number(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200102', '錯誤碼參Number(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200103', '多Language 標簽');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200371', 'IACTF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202701', 'Deposits 業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202702', 'Remittance 業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202703', 'HIP ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('233', '結清');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('234', 'Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('235', '重整');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('236', '展期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('237', 'Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3026', 'Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3027', 'Payment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3028', 'Remittance ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3029', 'Stock ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3030', 'Autopay ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3031', '1');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400060', 'Batch Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4001', '待銷戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4002', '關戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400720', '基礎Enquiry ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400721', 'Premium Enquiry ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400723', '最近1Month(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400724', 'Today ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400725', '最近3Month(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4010', 'Deposits Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4011', 'Loan Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4012', 'Credit Card Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4013', 'Securities A/C ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4014', 'Financial Flexibility ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402021', 'Current Day(s) Transation ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402022', '1 Week ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402023', '1 Month ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402024', '3 Months ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40430', 'Batch 批Times Times ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40731', 'All ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40732', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40733', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40735', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40736', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40737', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40738', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40739', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40740', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40741', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600001', '你Parents 在哪Unit 城市訂婚? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600002', '你爺爺出生地在哪? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600003', '你第一Times 出國Year 齡? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600004', '你初In學校Yes 哪裏? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600005', '你養第一Unit 寵物名字Yes 什麽? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600006', '你駕駛執照No. Yes 什麽? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600007', '你爸爸Date of Birth ? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600008', '你最喜歡餐廳名字Yes 什麽? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600009', '你小學三Year 級老師名字? ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600502', '特別聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600503', 'Insured person 聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600504', '聯豐亨【樂逍遙】');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600505', '太平洋保險');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60475', '標准Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60476', 'Deluxe Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60478', 'Basic Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60479', 'Super plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60480', 'Extreme plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60531', '分組一');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60532', '分組二');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60533', '分組三');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60534', '分組四');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700001', 'Grade ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700002', 'Points ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700003', 'Grade ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700004', 'Points ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700005', 'Grade ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700006', 'Points ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70001', 'Loan 應Repayment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700011', 'Up 學Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700012', 'Auto Loans ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700013', '1 Week ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700014', '二Week ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700015', '1 Month ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700016', '二Month(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700017', '3 Months ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700018', '六Month(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700019', '十二Month(s) ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70002', 'Loan 逾期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700020', '3To 7Unit 工作Day ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700021', '3To 7Unit 工作Day ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700022', '3To 7Unit 工作Day ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700023', '3To 7Unit 工作Day ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700024', 'TaiFung Online Bank Agreement 書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700025', 'Safety Questions Max 錯誤Times ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700026', 'One-time Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700027', 'Recurring by Month ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700028', 'Recurring by Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700029', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70003', 'Fix-Deposit To 期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700030', 'Relative ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700031', 'Parents ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700035', '3Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700036', '4Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700037', '5Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700038', '10Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700039', '30Year （後台Can 以維護）');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70004', 'Make an appointment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700042', '結清');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700043', 'Has been Cancelled ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700046', 'Has 重整');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700047', 'Cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700048', 'Yes ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700049', 'No ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70005', 'Financial Products Appointment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700052', 'ATMNo Katy is Agreement 文Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700053', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700054', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700055', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700056', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700057', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700058', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700059', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70006', '領取ATM card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700060', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700061', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700062', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700063', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700064', 'TFG');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700065', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70007', '領取Checkbook ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700073', 'Area 1 $#$Restricted Area (包括: In國、 Hong Kong 、 緬甸、 泰國、 馬來西亞、 New 加坡、 印尼、 菲律賓、 汶萊、 越南、 韓國、 柬浦寨、 老撾、 台灣、 Day Unit 、 尼泊爾、 巴基斯坦、 印度)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700074', 'District 二$#$Worldwide (美國除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700075', 'District 三$#$Worldwide ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700077', '6Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700078', '7Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700079', '8Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70008', '領取Paper Monthly Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700080', '9Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700082', '雇員');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700083', 'Employee ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700084', 'Company Unit 東');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700085', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70009', '領取Account 資金Balance Certificate ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700091', '穩健型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700092', '謹慎型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700093', '平衡型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700094', '進取型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700095', '投機型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700096', 'Stock Streaming Service Password ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700098', '澳洲元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700099', '加拿大元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70010', '生Day 節Day 祝福');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700100', 'CNY ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700101', 'HK ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700102', 'Day Unit 元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700103', 'Macau 元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700104', '紐西蘭元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700105', '瑞士法郎');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700106', '英鎊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700107', '美鈔');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700108', '歐羅');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700109', 'USD ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70011', 'Risk investment questionnaire Tenor To 期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70012', 'Insurance 起始Day ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70013', '旅遊Insurance Maturity ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700131', 'Credit Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700132', '保險業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700133', '11Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700134', '12Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700135', '13Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700136', '14Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700137', '15Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700138', '16Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700139', '17Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70014', 'Custom Reminder ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700140', '18Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700141', '19Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700142', '20Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700143', '21Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700144', '22Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700145', '23Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700146', '24Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700147', '25Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700148', '26Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700149', '27Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70015', 'Bank 假期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700150', '28Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700151', '你生Day 這Day(s) 裏, Yes My 祝福Yes My 問候: 祝開開心心, 心想事成. ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700152', '生Day , 就Yes 一Unit 起點, 一切從這裏開始! 祝你生Day 快樂! ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700153', '生Day 要喝彩, 壽星才愉快. 親愛朋友, 生Day 快樂. ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700154', '生Day 祝福你, 萬事順著你! ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700155', '祝You 壽與Day(s) 齊, 並祝美好明Day(s) ! ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70016', 'Appointment Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700171', 'Has passed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700172', 'Not by ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700173', 'Has Request ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700174', 'has been expired ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700176', 'TaiFung Online Bank Agreement 書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700181', '黃金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700182', '基金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700183', '國債');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700194', '核准');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700195', '部Unit 放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700196', 'All 放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700197', 'To 期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700198', '29Year ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700199', '押匯業務');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70020', 'No 作續期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700200', 'Account & Account 維護Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700201', '工商Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700202', 'Other Enquiry ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700203', '表揚/ 投訴/ 意見');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700204', 'Stock Financial Investment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70021', 'Principal Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700218', 'Accounts of assets ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700219', 'Cash assets ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70022', 'Unit 息Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700220', 'Stock Assets ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700221', 'Loan Assets ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700222', 'All Assets ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700223', 'Company Note 冊');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700224', '貿易促進局');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700225', 'Visa ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700226', 'Sponsor ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700227', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70023', 'Unit 息增額Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700235', 'ATM card / Auto 櫃員機');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700236', '電子渠道');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700237', '電信Payment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70024', 'Unit 息減額Surviving ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70025', 'Unit 息清還');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700250', '全額證明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700251', '定額證明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700252', '致各Yes 關Persons 士');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700253', 'Other ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700254', 'Mail ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700255', 'To receive ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700256', '1Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700257', '2Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700258', '3Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700259', '5Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700260', '4Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700261', 'English 簡體');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700262', 'English 繁體');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700263', 'English ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700264', 'Macau 身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700265', 'Hong Kong Identity Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700266', 'Mainland China 身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700267', 'Passport ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700268', 'All ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700269', 'Integer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700270', '等于');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700271', 'No 少于');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700272', 'Edit In');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700273', 'has been cancel ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700274', '審核No 通過');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700275', 'Submit 待審核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700276', '審核通過/Has 發布');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700277', 'Create ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700278', 'Updated ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700279', 'Delete ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700280', 'Undo ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700281', '停用');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700311', 'Request Success ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700312', 'Request Failed ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700313', '6Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700314', '7Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700315', '8Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700316', '9Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700317', '10Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700328', '+853');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700329', '+86');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700330', '+852');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700534', 'Mail ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700535', 'To receive ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700536', 'Mailing address ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700537', 'Receive address ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700538', 'Total Line 營業部Financial Investment 理財Center ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700551', 'Home Advertisement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700552', 'Product Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700553', '登陸頁Advertisement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700568', '標准Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700569', 'Deluxe Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700570', 'Basic Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700571', 'Super plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700572', 'Extreme plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700573', 'Luen Fung Hang Insurance Company Limited -標准Plan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700574', 'Terms & Conditions ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700575', 'Personal Loan ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700576', 'Personal Financial Management ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700577', 'Insurance Agreement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700578', 'ATMNo Katy is Agreement 文Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700579', 'First Login ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700580', '5Mobile No. Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700581', 'Online 通-理財Service 使用條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700582', '移動通-理財Service 使用條款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700583', '商務Online 理財Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700584', 'QR Cord Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700585', 'No Katy is ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700586', 'Autopay 直接Pay 授權書');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700587', 'Streaming Stock Quote Terms & Conditions ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700588', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700589', '監管Organization ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700590', '軟件Service Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700591', 'Online Bank Policy Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700592', 'Online Bank Privacy Privacy Policy 聲明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700639', '200');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700640', '54.00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700641', 'Hong Kong 居民身Unit 證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700655', '澳洲元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700656', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700657', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700658', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700659', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700660', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700661', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700662', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700663', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700664', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700665', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700666', 'TFG');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700667', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700816', '60.00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700900', 'Enquiry Not Add Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700901', 'iBanking Login ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700902', 'Online Transaction History ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700903', 'Delete 附屬Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700904', 'Add 附屬Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700905', 'Charge 扣費');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700906', 'Donation (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700907', '存折Report the loss (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700908', 'Activate Stock Streaming Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700909', 'Close Stock Streaming Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700910', 'iBanking Password Modify ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700911', 'Setting Safety Questions ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700912', 'Mobile No. 認證');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700913', 'Transaction Limit Setting ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700914', 'Verify ID (Forget Password 或Login Code )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700915', 'Verify Safety Questions (Forget Password )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700916', 'Reset Password (Forget Password )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700917', 'Verify Safety Questions (Forget Login Code )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700918', 'Transfer within own A/C (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700919', 'Transfer within own A/C (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700920', 'Third-Party Transfer (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700921', 'Third-Party Transfer (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700922', 'Transfer to BOCM (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700923', 'Transfer to BOCM (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700924', 'Batch Transfer (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700925', 'Batch Transfer (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700926', 'Enquiry 簽約第三者帳戶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700927', 'Add /Modify Third-Party accounts ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700928', 'Enquiry BOCM A/C ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700929', 'Add /Modify BOCM A/C ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700930', 'Add Appointment Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700931', 'Modify Pre-set Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700932', 'Appointment Status Modify ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700933', 'Manage Your Payees (Modify )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700934', 'Manage Your Payees (Delete )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700935', 'Manage Your Payees (Avatar Edit )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700936', 'Verify Third-Party account For the first time Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700937', 'Activate QR Cord Transfer Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700938', 'Activate Mobile No. Transfer Service ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700939', 'Add Remittance (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700940', 'Add Remittance (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700941', 'Activate Monthly e-Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700942', 'Close Monthly e-Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700943', 'Request Previous Monthly Statement ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700944', 'Travel Insurance Application (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700945', 'Travel Insurance Application (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700946', 'Modify Nickname ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700947', 'Suspend Account ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700948', 'Request Checkbook ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700949', 'Report loss of Checkbook ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700950', 'Report loss of Checkbook ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700951', '存折Report the loss ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700952', 'Assets Certification Request ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700953', 'Payment 稅收(Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700954', 'Payment 稅收(Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700955', '繳三費(Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700956', '繳三費(Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700957', 'Yes 限電視Payment (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700958', 'Yes 限電視Payment (Submit )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700959', 'Payment In國電信(Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700960', 'Payment In國電信(Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700961', 'Payment 社保(Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700962', 'Payment 社保(Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700963', 'Credit Card Repayment (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700964', 'Credit Card Repayment (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700965', 'Add Payee ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700966', 'Delete Payee ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700967', 'Modify Payee ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700968', 'Request Autopay ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700969', 'Modify Autopay ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700970', 'Delete Autopay ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700971', 'Donation (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700972', 'Portfolio ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700973', 'Stock Current Day(s) Transation ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700974', 'Stock Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700975', 'Current ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700976', 'Orders ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700977', 'Change (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700978', 'Get Delayed Price 時Stock Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700979', 'Cancel Order ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700980', 'Stock Transation Detail ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700981', 'Change (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700982', 'Stock Transaction within a Month ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700983', 'Can 供Request IPOList Enquiry ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700984', '認證New Unit 詳細Enquiry ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700985', '認證New Unit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700986', 'Securities A/C information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700987', 'Fund Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700988', 'Foreign Exchange (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700989', 'Foreign Exchange (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700990', 'New order to Fix-Deposit (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700991', 'New order to Fix-Deposit (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700992', 'Withdraw Fix-Deposit (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700993', 'Withdraw Fix-Deposit (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700994', 'iBanking Personal Information Modify ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700995', 'Modify Mobile No. ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700996', 'Pause iBanking ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700997', 'Financial Products Appointment ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700998', 'Loan Request ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700999', 'SMS Reminder Services Activate ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701000', 'SMS Reminder Services Close ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701001', 'Transaction Limit Setting ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701002', 'Mobile No. Transfer (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701003', 'Mobile No. Transfer (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701004', 'QR Cord Transfer (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701005', 'QR Cord Transfer (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701006', 'Add Insured person Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701007', 'Modify Insured person Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701008', 'Delete insured person Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701009', 'Request ATM card (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701010', 'Replace ATM Card (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701011', 'Report loss of ATM Card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701012', 'Suspend the ATM card ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701013', 'Appointment Service Management (Modify )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701014', 'Appointment Service Management (Cancel )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701015', 'Account Transaction History ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701016', 'Payment Collection via QR Code (Preview )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701017', 'Payment Collection via QR Code (Confirm )');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701018', 'Amend renewal instructions ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701019', 'Report the loss Fix Deposit Certification ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701020', 'Cancel Loan Request ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701021', 'Questionnaire ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701023', 'Enquiry Stock Information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701024', 'Buy /Sell ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701025', '持倉組合');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701026', 'Change /Cancel Order Preview ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701027', 'Cancel Order ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701028', 'Stock Transation Detail ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701029', 'Change Submit ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701030', 'Transaction within a Month ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701031', 'Can 供Request IPOList ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701032', 'IPO Subscription 詳細Enquiry ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701033', 'IPO Subscription ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701034', 'Securities A/C information ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701035', 'Fund Transfer ');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701036', 'Transation 檢查');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701037', 'Report the loss /Replace ATM Card ');



</body>
</html>