<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>

delete from PUB.TMP_NAME;

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060471', '地区一$#$指定地区(包括：中国、香港、缅甸、泰国、马来西亚、新加坡、印尼、菲律宾、汶莱、越南、韩国、柬浦寨、老挝、台湾、日本、尼泊尔、巴基斯坦、印度)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060472', '地区二$#$全球(美国除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('060473', '地区三$#$全球');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100001', '往来帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100002', '储蓄帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100003', '多币宝帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100004', '定期帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100005', '灵活理财帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100006', '股票帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100007', '贷款帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100008', '一般卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100009', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100011', '自动转帐付款证明书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100012', '往来月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100013', '多币宝压缩结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100014', 'MI斩仓单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100015', '定期结清单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100016', '储蓄帐户的压缩结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100017', 'MI结清单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100018', '亲临领取');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100019', '公司注册');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100020', '贸易促进局');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100021', '申请签证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100022', '赞助');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100023', '其它');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100024', '中文(简体)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100025', '中文(繁体)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100026', '英文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100027', '不动户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100028', '正常');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100029', '全部');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100030', '资产');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100031', '负债');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100032', '消费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100033', '管道');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100034', '批量');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100035', '投资');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100036', '奖励');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100037', '金额');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100038', '次数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100039', '批量转帐');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100040', '定投计划撤销');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100041', '加息赢签约');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100042', '网银中加挂借记卡或信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100043', '贵金属委托撤销');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100044', '信用卡还款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100045', '一站式转帐');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100046', '存入定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100047', '理财产品预约');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100048', '黄金定投开户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100049', '定投计划设置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100050', '生活缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100051', '基金开户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100052', '基金转帐');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100053', '个人贷款申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100055', '签约网银互联');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100056', '旅游保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100057', '其它');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100058', '同名户转帐');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100059', '第三者转帐');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100060', '转帐至中银澳门分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100062', '电汇');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100063', '信汇');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100065', '速汇金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100066', '汇入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100067', '汇出');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100068', '成功');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100069', '失败');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100070', '待处理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100071', '未知');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100072', '已审核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100073', '审核中');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100074', '未审核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100075', '不作续期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100076', '本金续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100077', '本息续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100078', '本息增额续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100079', '本息减额续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100080', '本息清还');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100081', '本人');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100082', '配偶');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100083', '家人');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100084', '子女');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100085', '男');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100086', '女');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100087', '指定地区(包括:中国、香港、缅甸等)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100088', '全球(美国除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100089', '全球(美国除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100090', '标准计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100091', '高级计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100092', '未婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100093', '已婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100094', '离婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100095', '未启动');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100096', '已启动');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100101', '楼宇按揭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100102', '升学贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100103', '汽车贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100104', '预期还款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100105', '正常还款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100106', '全额还款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100107', '部分还款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100108', '853');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100109', '86');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100110', '单次预约转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100111', '周期转帐');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100112', '每月一次');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100113', '每周一次');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100114', '收款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100115', '支款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100116', '第三方账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100117', '全部');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100118', '澳中银账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100119', '电费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100120', '水费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100121', '煤气费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100122', '电视费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100123', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100124', '3.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100125', '2.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100127', '2.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100128', '2.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100129', '1.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100130', '1.50%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100131', '1.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100132', '1.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100133', '0.75%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100134', '0.50%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100135', '0.25%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100136', '0.00%');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100137', '总行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100138', '新桥分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100139', '宝翠分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100140', '红街市分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100141', '黑沙环分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100142', '荷兰园分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100143', '十月初五街分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100144', '普京分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100145', '一山分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100146', '渡船街分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100147', '高士德分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100148', '筷子基分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100149', '百老汇分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100150', '新口岸分行');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100151', '1年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100152', '2年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100153', '星期一');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100154', '星期二');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100155', '星期三');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100156', '星期四');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100157', '星期五');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100158', '1');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100159', '2');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100160', '3');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100161', '4');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100162', '5');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100163', '6');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100164', '7');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100165', '8');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100166', '9');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100167', '10');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100168', '11');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100169', '12');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100170', '13');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100171', '14');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100172', '15');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100173', '16');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100174', '17');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100175', '18');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100176', '19');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100177', '20');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100178', '21');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100179', '22');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100180', '23');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100181', '24');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100182', '25');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100183', '26');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100184', '27');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100185', '28');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100186', '29');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100187', '30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100188', '31');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100200', '世界宣明会');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100201', '澳门红十字会');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100202', '澳门同善堂');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100203', '奥比斯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100204', '澳门明爱');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100205', '澳门聋人协会');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100206', '澳门弱智人士服务协会');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100207', '澳门扶康会');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100210', '地震');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100211', '水灾');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100212', '疾病');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100221', '汶川地震');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100224', '汶川水灾');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100227', '汶川疾病');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100230', '电费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100231', '水费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100232', '话费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100233', '税收');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100234', '电视费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100235', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100238', '督课中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100239', '大丰投资');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100240', '电讯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100242', '物业管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100243', '水电能源');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100280', '电信');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100281', '社保');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100282', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100283', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100300', '澳门电力公司');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100302', '自来水公司');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100303', '澳门电讯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100304', '港币');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100305', '澳币');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100307', '股票服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100308', '提款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100309', '贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100310', '外币兑换');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100311', '定期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100312', '转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100313', '保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100314', '汇款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100315', '保管箱');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100316', '存款证明书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100317', '月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100318', '提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100319', '外汇买卖');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100320', '金融投资理财中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100323', '预约理财产品服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100324', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100325', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100326', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100327', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100328', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100329', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100330', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100331', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100332', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100333', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100334', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100336', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100337', '澳门特别行政区居民身分证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100338', '香港居民身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100339', '中国身分证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100340', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100341', '中学');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100342', '大专');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100343', '大学或以上');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100344', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100345', '已婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100346', '未婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100347', '离婚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100348', '鳏寡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100349', '分别财产制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100350', '一般共同财产制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100351', '取得共同财产制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100352', '取得财产分享制');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100353', '自置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100354', '亲人拥有');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100355', '按揭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100356', '租用');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100357', '雇员');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100358', '东主');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100359', '公司股东');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100360', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100361', '薪金收入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100362', '经营收入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100363', '租金收入');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100364', '是');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100365', '否');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100366', '大丰银行调查问卷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100367', '未提交');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100368', '已提交');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100369', '未通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100370', '已通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100372', '冻结');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100373', '正常');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100374', '锁定');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100375', '待激活');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100431', '香港身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100432', '澳门识别证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100433', '澳门居民身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100434', '临时居民身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100435', '营业税档案编号');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100436', '九零登记收据');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100437', '九零登记无证行动');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100438', '非本地劳工证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100439', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100440', '澳门身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100441', '中国身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100442', '台湾');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100443', '09:00-10:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100444', '10:00-11:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100445', '11:00-12:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100446', '14:00-15:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100447', '15:00-16:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100448', '16:00-17:00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100449', '09:00-09:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100450', '10:00-10:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100451', '11:00-11:45');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100452', '14:45-15:30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100453', '15:45-16:30');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100454', '住宅');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100455', '车位');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100456', '商铺');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100457', '写字');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100458', '厂房');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100459', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100460', '一手');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100461', '二手');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100462', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100463', '现楼');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100464', '楼花');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100465', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100512', '澳门特别行政区居民身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100600', '本澳升学贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100601', '海外升学贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100667', '中国太平保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100668', '联丰亨保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100669', '保单条款(中文版)下载');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100670', '保单条款(英文版)下载');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100671', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100672', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100673', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100674', '');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100675', '是');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100676', '否');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100677', '中文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100678', '英文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100679', '有');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100680', '无');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100682', '氹仔');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100683', '路环');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100690', '澳门');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100900', '申请中');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100901', '已通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('100902', '未通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101001', '冻结');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101007', '部分放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101100', '由申请日起7个工作日之后，三个自然月之内');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('101101', '由申请日起5个工作日之后，三个自然月之内');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120001', '现时价');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120002', '延时价');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120003', '由股票账户转入关联存款户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('120004', '由关联存款户转入股票账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121001', '全数成盘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121002', '部份成盘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121003', '全数失败');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121004', '全数取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121005', '部份取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('121006', '尚未覆盘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14001', '已核准');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14002', '全额放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('14003', '到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200011', '基础参数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200012', '多语言页面标签');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200013', '错误码参数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200014', '温馨提示');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200101', '基础参数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200102', '错误码参数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200103', '多语言标签');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('200371', 'IACTF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202701', '存款业务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202702', '汇款业务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('202703', '楼宇按揭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('233', '结清');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('234', '取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('235', '重整');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('236', '展期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('237', '取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3026', '转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3027', '缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3028', '汇款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3029', '股票');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3030', '自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('3031', '1');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400060', '批量转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4001', '待销户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4002', '关户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400720', '基础查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400721', '高级查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400723', '最近1个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400724', '今天');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('400725', '最近3个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4010', '存款账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4011', '贷款账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4012', '信用卡账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4013', '股票账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('4014', '灵活理财');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402021', '当天交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402022', '一星期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402023', '一个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('402024', '三个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40430', '批量批次次数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40731', '全部');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40732', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40733', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40735', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40736', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40737', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40738', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40739', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40740', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('40741', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600001', '你的父母在哪个城市订婚的？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600002', '你爷爷的出生地在哪？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600003', '你第一次出国的年龄？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600004', '你初中的学校是哪里？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600005', '你养的第一个宠物的名字是什么？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600006', '你的驾驶执照的号码是什么？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600007', '你爸爸的出生日期？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600008', '你最喜欢的餐厅的名字是什么？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600009', '你小学三年级的老师名字？');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600502', '特别声明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600503', '投保人声明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600504', '联丰亨【乐逍遥】');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('600505', '太平洋保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60475', '标准计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60476', '高级计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60478', '基本计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60479', '超级计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60480', '至尊计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60531', '分组一');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60532', '分组二');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60533', '分组三');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('60534', '分组四');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700001', '等级');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700002', '积分');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700003', '等级');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700004', '积分');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700005', '等级');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700006', '积分');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70001', '贷款应还款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700011', '升学贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700012', '汽车贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700013', '一星期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700014', '二星期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700015', '一个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700016', '二个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700017', '三个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700018', '六个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700019', '十二个月');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70002', '贷款逾期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700020', '3到7个工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700021', '3到7个工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700022', '3到7个工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700023', '3到7个工作日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700024', '大丰网上银行协议书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700025', '安全问题最大错误次数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700026', '不循环');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700027', '按月循环');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700028', '按年循环');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700029', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70003', '定期到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700030', '亲戚');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700031', '父母');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700035', '3年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700036', '4年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700037', '5年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700038', '10年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700039', '30年（后台可以维护）');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70004', '预约开户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700042', '结清');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700043', '已取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700046', '已重整');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700047', '取消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700048', '是');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700049', '否');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70005', '预约理财产品');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700052', 'ATM无卡提现协议文本');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700053', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700054', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700055', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700056', 'AUD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700057', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700058', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700059', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70006', '领取提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700060', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700061', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700062', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700063', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700064', 'TFG');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700065', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70007', '领取支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700073', '地区一$#$指定地区(包括：中国、香港、缅甸、泰国、马来西亚、新加坡、印尼、菲律宾、汶莱、越南、韩国、柬浦寨、老挝、台湾、日本、尼泊尔、巴基斯坦、印度)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700074', '地区二$#$全球(美国除外)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700075', '地区三$#$全球');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700077', '6年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700078', '7年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700079', '8年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70008', '领取纸质月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700080', '9年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700082', '雇员');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700083', '东主');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700084', '公司股东');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700085', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70009', '领取账户资金余额证明书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700091', '稳健型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700092', '谨慎型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700093', '平衡型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700094', '进取型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700095', '投机型');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700096', '股票串流服务密码');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700098', '澳洲元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700099', '加拿大元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70010', '生日节日祝福');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700100', '人民币');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700101', '港元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700102', '日本元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700103', '澳门元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700104', '纽西兰元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700105', '瑞士法郎');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700106', '英镑');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700107', '美钞');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700108', '欧罗');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700109', '美元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70011', '风险投资问卷期限到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70012', '旅游保险起始日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70013', '旅游保险到期日');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700131', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700132', '保险业务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700133', '11年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700134', '12年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700135', '13年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700136', '14年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700137', '15年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700138', '16年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700139', '17年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70014', '自设提示');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700140', '18年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700141', '19年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700142', '20年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700143', '21年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700144', '22年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700145', '23年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700146', '24年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700147', '25年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700148', '26年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700149', '27年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70015', '银行假期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700150', '28年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700151', '你生日的这天里，有我的祝福有我的问候：祝开开心心，心想事成。');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700152', '生日，就是一个起点，一切从这里开始！祝你生日快乐！');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700153', '生日要喝彩，寿星才愉快。亲爱的朋友，生日快乐。');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700154', '生日祝福你，万事顺着你！');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700155', '祝您寿与天齐，并祝美好明天！');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70016', '预约转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700171', '已通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700172', '未通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700173', '已申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700174', '已过期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700176', '大丰网上银行协议书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700181', '黄金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700182', '基金');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700183', '国债');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700194', '核准');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700195', '部份放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700196', '全部放款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700197', '到期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700198', '29年');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700199', '押汇业务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70020', '不作续期');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700200', '开户及账户维护服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700201', '工商贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700202', '其他查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700203', '表扬/ 投诉/ 意见');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700204', '股票金融投资');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70021', '本金续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700218', '账户资产');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700219', '现金资产');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70022', '本息续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700220', '股票资产');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700221', '贷款资产');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700222', '全部资产');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700223', '公司注册');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700224', '贸易促进局');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700225', '签证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700226', '赞助');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700227', '其他');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70023', '本息增额续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700235', '提款卡/ 自动柜员机');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700236', '电子渠道');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700237', '电信缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70024', '本息减额续存');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('70025', '本息清还');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700250', '全额证明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700251', '定额证明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700252', '致各有关人士');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700253', '其它');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700254', '邮寄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700255', '亲临领取');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700256', '1份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700257', '2份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700258', '3份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700259', '5份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700260', '4份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700261', '中文简体');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700262', '中文繁体');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700263', '英文');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700264', '澳门身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700265', '香港身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700266', '大陆身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700267', '护照');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700268', '全数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700269', '整数');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700270', '等于');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700271', '不少于');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700272', '编辑中');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700273', '已撤销');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700274', '审核不通过');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700275', '提交待审核');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700276', '审核通过/已发布');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700277', '创建');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700278', '更新');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700279', '删除');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700280', '撤消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700281', '停用');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700311', '申请成功');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700312', '申请失败');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700313', '6份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700314', '7份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700315', '8份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700316', '9份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700317', '10份');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700328', '+853');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700329', '+86');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700330', '+852');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700534', '邮寄');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700535', '亲临领取');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700536', '邮寄地址');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700537', '领取地址');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700538', '总行营业部的金融投资理财中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700551', '首页广告');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700552', '产品资讯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700553', '登陆页广告');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700568', '标准计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700569', '高级计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700570', '基本计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700571', '超级计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700572', '至尊计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700573', '联丰亨保险-标准计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700574', '服务条款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700575', '个人贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700576', '个人理财');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700577', '旅游保险协议');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700578', 'ATM无卡提现协议文本');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700579', '首次登录');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700580', '5手机号转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700581', '网上通-理财服务使用条款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700582', '移动通-理财服务使用条款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700583', '商务网上理财服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700584', '二维码转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700585', '无卡提现');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700586', '自动转账直接付款授权书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700587', '串流报价服务条款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700588', '电子结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700589', '监管机构');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700590', '软件使用声明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700591', '网上银行保安资讯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700592', '网上银行隐私政策声明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700639', '200');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700640', '54.00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700641', '香港居民身份证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700655', '澳洲元');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700656', 'CAD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700657', 'CNY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700658', 'HKD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700659', 'JPY');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700660', 'MOP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700661', 'NZD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700662', 'CHF');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700663', 'GBP');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700664', 'USD');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700665', 'USN');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700666', 'TFG');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700667', 'EUR');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700816', '60.00');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700900', '查询未添加账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700901', '网银登录');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700902', '网上交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700903', '删除附属账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700904', '添加附属账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700905', '手续费扣费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700906', '爱心捐款(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700907', '存折报失(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700908', '开通股票串流服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700909', '关闭股票串流服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700910', '网上银行密码修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700911', '设置安全问题');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700912', '手机号认证');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700913', '交易限额设置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700914', '验证证件号(忘记密码或登录代号)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700915', '验证安全问题(忘记密码)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700916', '重置密码(忘记密码)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700917', '验证安全问题(忘记登录代号)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700918', '同名户转账(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700919', '同名户转账(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700920', '第三者转账(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700921', '第三者转账(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700922', '中银澳分行转账(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700923', '中银澳分行转账(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700924', '批量转账(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700925', '批量转账(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700926', '查询签约第三者帐户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700927', '添加/修改第三者账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700928', '查询中银澳分账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700929', '添加/修改中银澳分账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700930', '添加预约转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700931', '修改预约转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700932', '预约状态修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700933', '收款人名册管理(修改)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700934', '收款人名册管理(删除)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700935', '收款人名册管理(头像编辑)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700936', '验证第三者账号首次转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700937', '开通二维码转账服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700938', '开通手机号转账服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700939', '新增汇款(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700940', '新增汇款(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700941', '开通电子月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700942', '关闭电子月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700943', '申请过往月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700944', '申请旅游保险(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700945', '申请旅游保险(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700946', '修改别名');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700947', '冻结账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700948', '申请支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700949', '报失支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700950', '报失支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700951', '存折报失');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700952', '资产证明书申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700953', '缴费税收(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700954', '缴费税收(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700955', '缴三费(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700956', '缴三费(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700957', '有限电视缴费(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700958', '有限电视缴费(提交)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700959', '缴费中国电信(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700960', '缴费中国电信(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700961', '缴费社保(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700962', '缴费社保(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700963', '信用卡还款(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700964', '信用卡还款(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700965', '新增缴费单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700966', '删除缴费单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700967', '修改缴费单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700968', '申请自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700969', '修改自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700970', '删除自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700971', '爱心捐款(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700972', '投资组合');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700973', '股票当天交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700974', '股票信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700975', '现时价');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700976', '落盘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700977', '改盘(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700978', '获取延时报价时股票信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700979', '撤盘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700980', '股票交易详情');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700981', '改盘(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700982', '股票当月交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700983', '可供申请IPO列表查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700984', '认证新股详细查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700985', '认证新股');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700986', '股票账户资料');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700987', '按金调拨');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700988', '外汇买卖(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700989', '外汇买卖(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700990', '新造定期(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700991', '新造定期(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700992', '提取定期(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700993', '提取定期(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700994', '网银个人资料修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700995', '修改手机号');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700996', '暂停网银');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700997', '预约理财产品');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700998', '贷款申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('700999', '短讯提醒服务开通');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701000', '短讯提醒服务关闭');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701001', '交易限额设置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701002', '手机号转账(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701003', '手机号转账(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701004', '二维码转账(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701005', '二维码转账(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701006', '添加投保人信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701007', '修改投保人信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701008', '删除投保人信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701009', '申请提款卡(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701010', '补发提款卡(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701011', '报失提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701012', '冻结提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701013', '预约服务管理(修改)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701014', '预约服务管理(取消)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701015', '账户交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701016', '二维码收款(预览)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701017', '二维码收款(确认)');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701018', '更改续期方式');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701019', '报失定期存款证明书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701020', '取消贷款申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701021', '问卷填写');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701023', '查询股票信息');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701024', '买入/卖出');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701025', '持仓组合');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701026', '改盘/撤盘预览');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701027', '撤盘');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701028', '股票交易详情');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701029', '改盘提交');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701030', '当月交易');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701031', '可供申请IPO列表');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701032', '认购新股详细查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701033', '认购新股');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701034', '股票账户资料');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701035', '按金调拨');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701036', '交易检查');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('701037', '报失/补发提款卡');

</body>
</html>