<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="utf-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>Insert title here</title>
</head>
<body>

delete from PUB.TMP_NAME;

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP02001', '首页');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03000', '账户服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03001', '账户一览');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03009', '账户管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03010', '添加/删除账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03015', '冻结账户');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03023', '交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03024', '账户交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03027', '月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03028', '开通/取消电子结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03031', '下载电子结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03036', '申请过往月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03039', '支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03040', '申请支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03045', '报失支票簿');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03050', '存摺报失');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03055', '资产证明书申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP03060', '网上交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04000', '转账汇款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04001', '普通转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04011', '同名户转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04021', '第三者转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04031', '中银澳分行转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04041', '批量转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04061', '收款人名册管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04071', '转账交易查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04100', '二维码转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04101', '开通/关闭服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04111', '二维码转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04121', '二维码收款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04131', '交易记录查询/撤消');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04200', '手机号转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04201', '开通/关闭服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04211', '手机号转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04221', '交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04300', '网上汇款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04301', '汇款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04311', '交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP04400', '预约/周期转账汇款管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05000', '缴费支付');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05001', '网上缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05002', '缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05005', '交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05010', '管理缴费单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05022', '自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05023', '申请自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05030', '取消/修改自动转账');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05043', '爱心捐款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05044', '爱心捐款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05050', '交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP05200', '缴费单查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06000', '个人理财');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06001', '财富及投资总览');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06002', '外汇买卖');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06004', '外汇买卖');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06010', '交易记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06015', '定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06016', '新造定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06022', '提取定期存款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06028', '查看及更改续期方式');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06034', '风险承受能力评估');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06035', '风险承受能力评估');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06038', '旅游保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06039', '查看保费及资讯');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06040', '投保人管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06041', '查看评估等级');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06047', '购买旅游保险');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06054', '购买记录查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06057', '下载保单条款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06058', '下载索偿表格');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06059', '查看使用声明');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06060', '计算器');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06066', '报失定期存款证明书');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP06070', '金融资讯及工具');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07000', '信用卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07002', '信用卡申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07007', '网上缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07013', '优惠活动');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07015', '信用卡账户信息管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07021', '查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07022', '缴费');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07028', '查询信用卡结余');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07029', '交易查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07030', '查询交易记录');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07032', '查询电子月结单');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07038', '额度管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07039', '办理[月结单分期付款]');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07040', '[月结单分期付款]计划');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07041', '主卡额度申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07042', '附属卡额度申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07045', '查询交易记录');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07050', '礼品换领');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07051', '选择礼品');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07053', '换领礼品查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07056', '网上购物安保服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07057', '「一次性密码」网上保安服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP07061', '认证记录');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08000', '个人贷款');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08001', '个人贷款申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08002', '申请');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08008', '查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08015', '贷款详情查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08020', '贷款结欠查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08023', '还款明细查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP08027', '抵押物业资料查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09000', '提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09001', '申请提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09011', '补发提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09016', '报失提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP09022', '冻结提款卡');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10000', '预约服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10009', '预约理财产品服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10013', '预约服务管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10400', '预约/周期转账汇款管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10500', '网点预约排队');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP10600', '网点远程取号');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11000', '安全中心');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11001', '个人信息管理');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11007', '网上银行密码修改');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11010', '短讯提醒服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11021', '安全密码器冻结');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11024', '交易限额设置');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11028', '短讯密码认证设定');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11029', '关闭短讯密码认证版');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11035', '修改已绑定之手机号码');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11040', '暂停网银服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11044', '调查问卷');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11045', '问卷填写');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP11048', '问卷记录查看');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12000', '股票服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12001', '股票买卖');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12002', '认购新股');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12004', '认购结果查询');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12005', '串流股票报价服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12019', '查看新股资讯及认购');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12026', '股票账户资料');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12027', '按金调拨');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12034', '申请串流股票报价服务');

INSERT INTO PUB.TMP_NAME (R_ID, SRC_NAME)
VALUES ('PP12038', '取消串流股票报价服务');



</body>
</html>